### ISSUE TITLE
Clarification wanted

### ISSUE THREAD

**Issue by DaftVagabond** [BackTrak/StreamDeckNvidiaBroadcastPlugin#1]
Sorry, I know I'm new at this, but I cannot figure out how to build this plugin.

And for the installation.bat, I keep getting the same issue during installation, that the .sdPlugin file cannot be found.

I'm hoping for some clarification with how I can use this, please.

**Comment by BackTrak** [comment]
Hi! Thanks for taking an interest in the plugin. You will need to adjust the install.bat to your local environment. I'm willing to bet it's this line: 

%DISTRIBUTION_TOOL% -b -i C:\Source\Home\StreamDeckNvidiaBroadcastPlugin\bin\Debug\com.zaphop.nvidiabroadcast.sdPlugin -o %OUTPUT_DIR%

Modify this path to point to your local build directory if it doesn't match mine. 

I'm planning to submit some plugins to the streamdeck store to make this easier. 

Good luck!

**Comment by BackTrak** [comment]
Clancey updated the install.bat to clean this up. Thanks!
