### ISSUE TITLE
Buttons not working

### ISSUE THREAD

**Issue by cezou** [BackTrak/StreamDeckNvidiaBroadcastPlugin#3]
When I use the Plugin, I can see the logos going green or grey as modes or activated or not but I cant press the Buttons to switch between mods, it doesnt Work. I tried to close NVIDIA Broadcast, to restart Elgato Stream Deck as administrator and to restart my PC.

**Comment by BackTrak** [comment]
Hello, could you please tell me which version of NVidia Broadcast you are using? You can find it in NVidia Broadcast by clicking the settings cog in the top right. It should be a number like 1.4.0.29. 

If you open the NVidia Broadcast app, click on Camera, you should see a list of effects. When you press the buttons on the stream deck, do you see the toggles move in NVidia Broadcast? 

![toggle](https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/assets/1970304/98621890-a817-4ccd-aec5-b9a24b592138)

**Comment by Max0904** [comment]
Hi hope this finds you well! I'm having the same problem, I can see the logo turning green when I activate manually in Nvidia Broadcast App, but trying to togle using the stream deck doesn't work! I was wondering if this is something related to the language of my Nvidia Broadcast app, My system is in Portuguese from Brazil so I cannot change the language of Nvidia Broadcast that is also in Portuguese. Could you please help?

**Comment by BackTrak** [comment]
Hi, could you please attach this file: %ProgramData%\\NVIDIA\\NVIDIABroadcast\\Settings\\NvVirtualCamera\\config.json so I can see if there is some language difference in your version?

Thanks!

**Comment by BackTrak** [comment]
Hi @Max0904, @cezou, I added localization support to the plugin, if you want to give it a shot: https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/releases/download/v1.1.0.0/com.zaphop.nvidiabroadcast.sdPlugin.zip

Quit the StreamDeck app completely, then you should be able to copy the contents of the zip to:

%AppData%\Elgato\StreamDeck\Plugins\com.zaphop.nvidiabroadcast.sdPlugin


If you can confirm it works for you, I will submit the update to Elgato. 

Thanks!

**Comment by Max0904** [comment]
> Can you also send a screen shot, similar to the one I have above, showing the effect filter? I'd like to see if the text in the combo boxes is localized to your language.

Hello, thanks for the replay, here's the config.json and the screenshot, whit this new update with localization support looks like the buttons are not showing if it's enable or not, as this screenshot shows

 Nvidia Broadcast is activated but on stream deck it's grayed.
[config.json](https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/files/14232404/config.json)
![Screenshot_3](https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/assets/25615294/aa652236-39de-4596-b899-194adb2b7b79)

Just to you know here's the translation for each item:

Remoção de ruído do vídeo (beta) = Video noise removal (beta)
Desfoque do fundo = Background blur
Substituição do fundo = Background replacement
Remover Fundo = Background removal
Enquadramento automático = Auto frame
Contato Visual (beta) = Eye contact (beta)
Vinheta = Vignette


Hope it helps.

**Comment by BackTrak** [comment]
Hi @Max0904, I had a small error in the release version that is corrected now. Could you please try again with this one?

https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/releases/download/v1.1.0.1/com.zaphop.nvidiabroadcast.sdPlugin.zip

Thanks!

**Comment by Max0904** [comment]
> Hi @Max0904, I had a small error in the release version that is corrected now. Could you please try again with this one?
> 
> https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/releases/download/v1.1.0.1/com.zaphop.nvidiabroadcast.sdPlugin.zip
> 
> Thanks!

Thank you so much! Now it's working everything!

**Comment by BackTrak** [comment]
Great! Thanks for confirming, I will send the update to the store today!
