### ISSUE TITLE
ideas and suggestions.

### ISSUE THREAD

**Issue by 1tzelG** [BackTrak/StreamDeckNvidiaBroadcastPlugin#7]
Hi. please add more functionality like adjustability, add/remove/adjust effects, change/toggle/on-off audio/video devices. i tried to install the pre-release but don't work. i like this plugin. is super useful but need more polish and functions. please consider every option like Elgato Camera Hub plugin as example.

Thank you for your great work, will help a lot much people include me.

**Comment by BackTrak** [comment]
Hi Danitza, 

This is complete and is currently submitted to Elgato marketplace. It should be available for you to use via marketplace update in a few days depending on their review. When I made the first version, I wasn't sure if anyone else would use it, but I'm happy to hear that you like it!

If you want to try the pre-release, copy the contents of the zip into 

%APPDATA%\Elgato\StreamDeck\Plugins\com.zaphop.nvidiabroadcast.sdPlugin

And then restart StreamDeck (right click on taskbar StreamDeck icon, click Quit), or reboot your computer.

Thank you for your suggestions and kind words!

**Comment by 1tzelG** [comment]
it worked, but, still being bad integration, and still don't like it, needs too much job for now.

what you have to do, is set 2 slots for each category tab on the broadcast app, so in that way, we can have bottons to change the effects of each slot, and see it reflected on the slot buttons into the Stream Deck, and press each slot button to toggle on/off. the idea is when a effect is asigned to a slot (i will refer to the effects button toggle like this), there's text to see which effect is asigned and if it's on or off.
You can add a button type/category on the plugin, where in his options, we can assign what we want, i mean, a drop down bar which contains the Nvidia Broadcast specific tab, Camera/Microphone/Speakers separately, to choose one of them, and another bar, which controls which effect we wish, and to which specific slot we want it. also the hability to assign a button to adjust them in + or - that is we need. i'm spanish ¿it's understandable?. you can text me through discord with same username without ''#''.  i dunno how much explain me better but i will cooperate to convert this into something awesome and useful. i'm very interested and i will be using it so much. you can being based on ideas like Elgato plugins like Camera Hub or Camera Control by BarRaider. check them out how works and assign a page for them to catch the idea how works.  kisses.

**Comment by 1tzelG** [comment]
i mean something like this and so on. 
![image](https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/assets/156023355/063a0096-9942-4bdb-a6d3-90c1bc91e4f4)

**Comment by 1tzelG** [comment]
long press on Toggle slot to access effect adjustability. or just simply the fact can assign another page or moar buttons if the deck is more bigger to fit them. this is my setup for audio and cameras. i use voicemeeter banana with the free 6 button mobile deck.
![image](https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/assets/156023355/5f07b375-ea49-40d3-9a53-db5e8ddb5ac2)

![image](https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/assets/156023355/a22fb07d-957b-4835-af69-c18a4b0df97f)

![image](https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/assets/156023355/b77add29-2765-4444-969b-3cb9b94207fd)

![image](https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/assets/156023355/8f9ca668-4bf0-48d0-b4ac-7c9947360e05)

![image](https://github.com/BackTrak/StreamDeckNvidiaBroadcastPlugin/assets/156023355/04e9e332-ee21-4f38-a523-a4fafb656a84)

i hope you get some inspiration from this.

**Comment by 1tzelG** [comment]
Can we talk on discord? text me. same name without #.
